name: Faster Digital
favicon: null
layout_spectrum: 0.6345952590927482
typography_spectrum: 0.6944074812345207
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.1520028447266668
  lightness: 0.6211999717634171
  saturation: 0.012825021520256996
  rhythmicContrast: 0.2683197995647788
purpose: []
